schedule:
  time: 5000
logger:
  level: info
  location: app.log
server:
  port: 9091
spring:
  datasource:
    url: jdbc:h2:mem:jobsdb
    driverClassName: org.h2.Driver
    username: rootAdmin
    password: password123$
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
